name: Cypress Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes Cypress
        run: npx cypress run

      - name: Gerar relatório
        run: |
          npx mochawesome-merge cypress/reports/*.json > cypress/reports/report.json
          npx marge cypress/reports/report.json -f report -o cypress/reports

      - name: Upload dos relatórios
        uses: actions/upload-artifact@v4
        with:
          name: cypress-report
          path: cypress/reports